class AlignmentWarEffortDonationResultEnum:
        
    WAR_EFFORT_DONATION_SUCCESS:int = 0;
        
    WAR_EFFORT_DONATION_ERROR_NOT_ENOUGH_KAMAS:int = 1;
        
    WAR_EFFORT_DONATION_ERROR_INVALID_ALIGNMENT:int = 2;
        
    WAR_EFFORT_DONATION_ERROR_KAMAS_LIMIT_REACH:int = 3;
        
    WAR_EFFORT_DONATION_ERROR_UNKNOWN:int = 4;