class SpellModifierTypeEnum:

    INVALID_MODIFICATION = 0
    RANGEABLE = 1
    DAMAGE = 2
    BASE_DAMAGE = 3
    HEAL_BONUS = 4
    AP_COST = 5
    CAST_INTERVAL = 6
    CRITICAL_HIT_BONUS = 7
    CAST_LINE = 8
    LOS = 9
    MAX_CAST_PER_TURN = 10
    MAX_CAST_PER_TARGET = 11
    RANGE_MAX = 12
    RANGE_MIN = 13
    OCCUPIED_CELL = 14
    FREE_CELL = 15
    VISIBLE_TARGET = 16
    PORTAL_FREE_CELL = 17
    PORTAL_PROJECTION = 18