class SubEntityBindingPointCategoryEnum:

    HOOK_POINT_CATEGORY_UNUSED: int = 0

    HOOK_POINT_CATEGORY_PET: int = 1

    HOOK_POINT_CATEGORY_MOUNT_DRIVER: int = 2

    HOOK_POINT_CATEGORY_LIFTED_ENTITY: int = 3

    HOOK_POINT_CATEGORY_BASE_BACKGROUND: int = 4

    HOOK_POINT_CATEGORY_MERCHANT_BAG: int = 5

    HOOK_POINT_CATEGORY_BASE_FOREGROUND: int = 6

    HOOK_POINT_CATEGORY_PET_FOLLOWER: int = 7

    HOOK_POINT_CATEGORY_UNDERWATER_BUBBLES: int = 8

    def __init__(self):
        super().__init__()
