class ActionIdProtocol:

    ACTION_QUEST_CHECK_STARTED_OBJECTIVES:int = 35

    ACTION_CHARACTER_ACTION_POINTS_USE:int = 102

    ACTION_CHARACTER_MOVEMENT_POINTS_USE:int = 129

    ACTION_CHARACTER_INVENTORY_ADD_ITEM_NOCHECK:int = 209

    ACTION_FIGHT_SPELL_DODGED_PA:int = 308

    ACTION_FIGHT_SPELL_DODGED_PM:int = 309

    ACTION_CHARACTER_UPDATE_BOOST:int = 515

    ACTION_PNJ_REMOVE_RIDE:int = 938

    ACTION_SHOW_ALIGNMENT:int = 960

    ACTION_SHOW_GRADE:int = 961

    ACTION_SHOW_LEVEL:int = 962

    ACTION_ITEM_EXPIRATION:int = 2833

    ACTION_CHARACTER_BOOST_THRESHOLD:int = 2872

    def __init__(self):
        super().__init__()
