//
// Autogenerated by Thrift Compiler (0.16.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;
var Int64 = require('node-int64');


var ttypes = require('./pyd2botService_types');
//HELPER FUNCTIONS AND STRUCTURES

var Pyd2botService_fetchAccountCharacters_args = function(args) {
  this.login = null;
  this.password = null;
  this.certId = null;
  this.certHash = null;
  if (args) {
    if (args.login !== undefined && args.login !== null) {
      this.login = args.login;
    }
    if (args.password !== undefined && args.password !== null) {
      this.password = args.password;
    }
    if (args.certId !== undefined && args.certId !== null) {
      this.certId = args.certId;
    }
    if (args.certHash !== undefined && args.certHash !== null) {
      this.certHash = args.certHash;
    }
  }
};
Pyd2botService_fetchAccountCharacters_args.prototype = {};
Pyd2botService_fetchAccountCharacters_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.login = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.password = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.certId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.certHash = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Pyd2botService_fetchAccountCharacters_args.prototype.write = function(output) {
  output.writeStructBegin('Pyd2botService_fetchAccountCharacters_args');
  if (this.login !== null && this.login !== undefined) {
    output.writeFieldBegin('login', Thrift.Type.STRING, 1);
    output.writeString(this.login);
    output.writeFieldEnd();
  }
  if (this.password !== null && this.password !== undefined) {
    output.writeFieldBegin('password', Thrift.Type.STRING, 2);
    output.writeString(this.password);
    output.writeFieldEnd();
  }
  if (this.certId !== null && this.certId !== undefined) {
    output.writeFieldBegin('certId', Thrift.Type.I32, 3);
    output.writeI32(this.certId);
    output.writeFieldEnd();
  }
  if (this.certHash !== null && this.certHash !== undefined) {
    output.writeFieldBegin('certHash', Thrift.Type.STRING, 4);
    output.writeString(this.certHash);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Pyd2botService_fetchAccountCharacters_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = Thrift.copyList(args.success, [ttypes.Character]);
    }
  }
};
Pyd2botService_fetchAccountCharacters_result.prototype = {};
Pyd2botService_fetchAccountCharacters_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        this.success = [];
        var _rtmp36 = input.readListBegin();
        var _size5 = _rtmp36.size || 0;
        for (var _i7 = 0; _i7 < _size5; ++_i7) {
          var elem8 = null;
          elem8 = new ttypes.Character();
          elem8.read(input);
          this.success.push(elem8);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Pyd2botService_fetchAccountCharacters_result.prototype.write = function(output) {
  output.writeStructBegin('Pyd2botService_fetchAccountCharacters_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter9 in this.success) {
      if (this.success.hasOwnProperty(iter9)) {
        iter9 = this.success[iter9];
        iter9.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Pyd2botService_runSession_args = function(args) {
  this.login = null;
  this.password = null;
  this.certId = null;
  this.certHash = null;
  this.sessionJson = null;
  if (args) {
    if (args.login !== undefined && args.login !== null) {
      this.login = args.login;
    }
    if (args.password !== undefined && args.password !== null) {
      this.password = args.password;
    }
    if (args.certId !== undefined && args.certId !== null) {
      this.certId = args.certId;
    }
    if (args.certHash !== undefined && args.certHash !== null) {
      this.certHash = args.certHash;
    }
    if (args.sessionJson !== undefined && args.sessionJson !== null) {
      this.sessionJson = args.sessionJson;
    }
  }
};
Pyd2botService_runSession_args.prototype = {};
Pyd2botService_runSession_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.login = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.password = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.certId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.certHash = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRING) {
        this.sessionJson = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Pyd2botService_runSession_args.prototype.write = function(output) {
  output.writeStructBegin('Pyd2botService_runSession_args');
  if (this.login !== null && this.login !== undefined) {
    output.writeFieldBegin('login', Thrift.Type.STRING, 1);
    output.writeString(this.login);
    output.writeFieldEnd();
  }
  if (this.password !== null && this.password !== undefined) {
    output.writeFieldBegin('password', Thrift.Type.STRING, 2);
    output.writeString(this.password);
    output.writeFieldEnd();
  }
  if (this.certId !== null && this.certId !== undefined) {
    output.writeFieldBegin('certId', Thrift.Type.I32, 3);
    output.writeI32(this.certId);
    output.writeFieldEnd();
  }
  if (this.certHash !== null && this.certHash !== undefined) {
    output.writeFieldBegin('certHash', Thrift.Type.STRING, 4);
    output.writeString(this.certHash);
    output.writeFieldEnd();
  }
  if (this.sessionJson !== null && this.sessionJson !== undefined) {
    output.writeFieldBegin('sessionJson', Thrift.Type.STRING, 5);
    output.writeString(this.sessionJson);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Pyd2botService_runSession_result = function(args) {
};
Pyd2botService_runSession_result.prototype = {};
Pyd2botService_runSession_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Pyd2botService_runSession_result.prototype.write = function(output) {
  output.writeStructBegin('Pyd2botService_runSession_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Pyd2botServiceClient = exports.Client = function(output, pClass) {
  this.output = output;
  this.pClass = pClass;
  this._seqid = 0;
  this._reqs = {};
};
Pyd2botServiceClient.prototype = {};
Pyd2botServiceClient.prototype.seqid = function() { return this._seqid; };
Pyd2botServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };

Pyd2botServiceClient.prototype.fetchAccountCharacters = function(login, password, certId, certHash, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_fetchAccountCharacters(login, password, certId, certHash);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_fetchAccountCharacters(login, password, certId, certHash);
  }
};

Pyd2botServiceClient.prototype.send_fetchAccountCharacters = function(login, password, certId, certHash) {
  var output = new this.pClass(this.output);
  var params = {
    login: login,
    password: password,
    certId: certId,
    certHash: certHash
  };
  var args = new Pyd2botService_fetchAccountCharacters_args(params);
  try {
    output.writeMessageBegin('fetchAccountCharacters', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

Pyd2botServiceClient.prototype.recv_fetchAccountCharacters = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Pyd2botService_fetchAccountCharacters_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('fetchAccountCharacters failed: unknown result');
};

Pyd2botServiceClient.prototype.runSession = function(login, password, certId, certHash, sessionJson, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_runSession(login, password, certId, certHash, sessionJson);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_runSession(login, password, certId, certHash, sessionJson);
  }
};

Pyd2botServiceClient.prototype.send_runSession = function(login, password, certId, certHash, sessionJson) {
  var output = new this.pClass(this.output);
  var params = {
    login: login,
    password: password,
    certId: certId,
    certHash: certHash,
    sessionJson: sessionJson
  };
  var args = new Pyd2botService_runSession_args(params);
  try {
    output.writeMessageBegin('runSession', Thrift.MessageType.ONEWAY, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    this.output.flush();
    var callback = this._reqs[this.seqid()] || function() {};
    delete this._reqs[this.seqid()];
    callback(null);
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};
var Pyd2botServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
};
Pyd2botServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
};
Pyd2botServiceProcessor.prototype.process_fetchAccountCharacters = function(seqid, input, output) {
  var args = new Pyd2botService_fetchAccountCharacters_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.fetchAccountCharacters.length === 4) {
    Q.fcall(this._handler.fetchAccountCharacters.bind(this._handler),
      args.login,
      args.password,
      args.certId,
      args.certHash
    ).then(function(result) {
      var result_obj = new Pyd2botService_fetchAccountCharacters_result({success: result});
      output.writeMessageBegin("fetchAccountCharacters", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("fetchAccountCharacters", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.fetchAccountCharacters(args.login, args.password, args.certId, args.certHash, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new Pyd2botService_fetchAccountCharacters_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("fetchAccountCharacters", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("fetchAccountCharacters", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
Pyd2botServiceProcessor.prototype.process_runSession = function(seqid, input, output) {
  var args = new Pyd2botService_runSession_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.runSession(args.login, args.password, args.certId, args.certHash, args.sessionJson);
};
