//
// Autogenerated by Thrift Compiler (0.16.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;
var Int64 = require('node-int64');


var ttypes = require('./pyd2botService_types');
//HELPER FUNCTIONS AND STRUCTURES

var Pyd2botService_getApiKey_args = function(args) {
  this.login = null;
  this.password = null;
  this.certId = null;
  this.certHash = null;
  if (args) {
    if (args.login !== undefined && args.login !== null) {
      this.login = args.login;
    }
    if (args.password !== undefined && args.password !== null) {
      this.password = args.password;
    }
    if (args.certId !== undefined && args.certId !== null) {
      this.certId = args.certId;
    }
    if (args.certHash !== undefined && args.certHash !== null) {
      this.certHash = args.certHash;
    }
  }
};
Pyd2botService_getApiKey_args.prototype = {};
Pyd2botService_getApiKey_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.login = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.password = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.certId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.certHash = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Pyd2botService_getApiKey_args.prototype.write = function(output) {
  output.writeStructBegin('Pyd2botService_getApiKey_args');
  if (this.login !== null && this.login !== undefined) {
    output.writeFieldBegin('login', Thrift.Type.STRING, 1);
    output.writeString(this.login);
    output.writeFieldEnd();
  }
  if (this.password !== null && this.password !== undefined) {
    output.writeFieldBegin('password', Thrift.Type.STRING, 2);
    output.writeString(this.password);
    output.writeFieldEnd();
  }
  if (this.certId !== null && this.certId !== undefined) {
    output.writeFieldBegin('certId', Thrift.Type.I32, 3);
    output.writeI32(this.certId);
    output.writeFieldEnd();
  }
  if (this.certHash !== null && this.certHash !== undefined) {
    output.writeFieldBegin('certHash', Thrift.Type.STRING, 4);
    output.writeString(this.certHash);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Pyd2botService_getApiKey_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
Pyd2botService_getApiKey_result.prototype = {};
Pyd2botService_getApiKey_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Pyd2botService_getApiKey_result.prototype.write = function(output) {
  output.writeStructBegin('Pyd2botService_getApiKey_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Pyd2botService_fetchAccountCharacters_args = function(args) {
  this.login = null;
  this.password = null;
  this.certId = null;
  this.certHash = null;
  this.apiKey = null;
  if (args) {
    if (args.login !== undefined && args.login !== null) {
      this.login = args.login;
    }
    if (args.password !== undefined && args.password !== null) {
      this.password = args.password;
    }
    if (args.certId !== undefined && args.certId !== null) {
      this.certId = args.certId;
    }
    if (args.certHash !== undefined && args.certHash !== null) {
      this.certHash = args.certHash;
    }
    if (args.apiKey !== undefined && args.apiKey !== null) {
      this.apiKey = args.apiKey;
    }
  }
};
Pyd2botService_fetchAccountCharacters_args.prototype = {};
Pyd2botService_fetchAccountCharacters_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.login = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.password = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.certId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.certHash = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRING) {
        this.apiKey = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Pyd2botService_fetchAccountCharacters_args.prototype.write = function(output) {
  output.writeStructBegin('Pyd2botService_fetchAccountCharacters_args');
  if (this.login !== null && this.login !== undefined) {
    output.writeFieldBegin('login', Thrift.Type.STRING, 1);
    output.writeString(this.login);
    output.writeFieldEnd();
  }
  if (this.password !== null && this.password !== undefined) {
    output.writeFieldBegin('password', Thrift.Type.STRING, 2);
    output.writeString(this.password);
    output.writeFieldEnd();
  }
  if (this.certId !== null && this.certId !== undefined) {
    output.writeFieldBegin('certId', Thrift.Type.I32, 3);
    output.writeI32(this.certId);
    output.writeFieldEnd();
  }
  if (this.certHash !== null && this.certHash !== undefined) {
    output.writeFieldBegin('certHash', Thrift.Type.STRING, 4);
    output.writeString(this.certHash);
    output.writeFieldEnd();
  }
  if (this.apiKey !== null && this.apiKey !== undefined) {
    output.writeFieldBegin('apiKey', Thrift.Type.STRING, 5);
    output.writeString(this.apiKey);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Pyd2botService_fetchAccountCharacters_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = Thrift.copyList(args.success, [ttypes.Character]);
    }
  }
};
Pyd2botService_fetchAccountCharacters_result.prototype = {};
Pyd2botService_fetchAccountCharacters_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        this.success = [];
        var _rtmp31 = input.readListBegin();
        var _size0 = _rtmp31.size || 0;
        for (var _i2 = 0; _i2 < _size0; ++_i2) {
          var elem3 = null;
          elem3 = new ttypes.Character();
          elem3.read(input);
          this.success.push(elem3);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Pyd2botService_fetchAccountCharacters_result.prototype.write = function(output) {
  output.writeStructBegin('Pyd2botService_fetchAccountCharacters_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter4 in this.success) {
      if (this.success.hasOwnProperty(iter4)) {
        iter4 = this.success[iter4];
        iter4.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Pyd2botService_runSession_args = function(args) {
  this.login = null;
  this.password = null;
  this.certId = null;
  this.certHash = null;
  this.apiKey = null;
  this.sessionJson = null;
  if (args) {
    if (args.login !== undefined && args.login !== null) {
      this.login = args.login;
    }
    if (args.password !== undefined && args.password !== null) {
      this.password = args.password;
    }
    if (args.certId !== undefined && args.certId !== null) {
      this.certId = args.certId;
    }
    if (args.certHash !== undefined && args.certHash !== null) {
      this.certHash = args.certHash;
    }
    if (args.apiKey !== undefined && args.apiKey !== null) {
      this.apiKey = args.apiKey;
    }
    if (args.sessionJson !== undefined && args.sessionJson !== null) {
      this.sessionJson = args.sessionJson;
    }
  }
};
Pyd2botService_runSession_args.prototype = {};
Pyd2botService_runSession_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.login = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.password = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.certId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.certHash = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRING) {
        this.apiKey = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.STRING) {
        this.sessionJson = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Pyd2botService_runSession_args.prototype.write = function(output) {
  output.writeStructBegin('Pyd2botService_runSession_args');
  if (this.login !== null && this.login !== undefined) {
    output.writeFieldBegin('login', Thrift.Type.STRING, 1);
    output.writeString(this.login);
    output.writeFieldEnd();
  }
  if (this.password !== null && this.password !== undefined) {
    output.writeFieldBegin('password', Thrift.Type.STRING, 2);
    output.writeString(this.password);
    output.writeFieldEnd();
  }
  if (this.certId !== null && this.certId !== undefined) {
    output.writeFieldBegin('certId', Thrift.Type.I32, 3);
    output.writeI32(this.certId);
    output.writeFieldEnd();
  }
  if (this.certHash !== null && this.certHash !== undefined) {
    output.writeFieldBegin('certHash', Thrift.Type.STRING, 4);
    output.writeString(this.certHash);
    output.writeFieldEnd();
  }
  if (this.apiKey !== null && this.apiKey !== undefined) {
    output.writeFieldBegin('apiKey', Thrift.Type.STRING, 5);
    output.writeString(this.apiKey);
    output.writeFieldEnd();
  }
  if (this.sessionJson !== null && this.sessionJson !== undefined) {
    output.writeFieldBegin('sessionJson', Thrift.Type.STRING, 6);
    output.writeString(this.sessionJson);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Pyd2botService_runSession_result = function(args) {
};
Pyd2botService_runSession_result.prototype = {};
Pyd2botService_runSession_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Pyd2botService_runSession_result.prototype.write = function(output) {
  output.writeStructBegin('Pyd2botService_runSession_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Pyd2botService_fetchBreedSpells_args = function(args) {
  this.breedId = null;
  if (args) {
    if (args.breedId !== undefined && args.breedId !== null) {
      this.breedId = args.breedId;
    }
  }
};
Pyd2botService_fetchBreedSpells_args.prototype = {};
Pyd2botService_fetchBreedSpells_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.breedId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Pyd2botService_fetchBreedSpells_args.prototype.write = function(output) {
  output.writeStructBegin('Pyd2botService_fetchBreedSpells_args');
  if (this.breedId !== null && this.breedId !== undefined) {
    output.writeFieldBegin('breedId', Thrift.Type.I32, 1);
    output.writeI32(this.breedId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Pyd2botService_fetchBreedSpells_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = Thrift.copyList(args.success, [ttypes.Spell]);
    }
  }
};
Pyd2botService_fetchBreedSpells_result.prototype = {};
Pyd2botService_fetchBreedSpells_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        this.success = [];
        var _rtmp36 = input.readListBegin();
        var _size5 = _rtmp36.size || 0;
        for (var _i7 = 0; _i7 < _size5; ++_i7) {
          var elem8 = null;
          elem8 = new ttypes.Spell();
          elem8.read(input);
          this.success.push(elem8);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Pyd2botService_fetchBreedSpells_result.prototype.write = function(output) {
  output.writeStructBegin('Pyd2botService_fetchBreedSpells_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter9 in this.success) {
      if (this.success.hasOwnProperty(iter9)) {
        iter9 = this.success[iter9];
        iter9.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Pyd2botService_fetchJobsInfosJson_args = function(args) {
};
Pyd2botService_fetchJobsInfosJson_args.prototype = {};
Pyd2botService_fetchJobsInfosJson_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Pyd2botService_fetchJobsInfosJson_args.prototype.write = function(output) {
  output.writeStructBegin('Pyd2botService_fetchJobsInfosJson_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Pyd2botService_fetchJobsInfosJson_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
Pyd2botService_fetchJobsInfosJson_result.prototype = {};
Pyd2botService_fetchJobsInfosJson_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Pyd2botService_fetchJobsInfosJson_result.prototype.write = function(output) {
  output.writeStructBegin('Pyd2botService_fetchJobsInfosJson_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Pyd2botService_moveToVertex_args = function(args) {
  this.vertex = null;
  if (args) {
    if (args.vertex !== undefined && args.vertex !== null) {
      this.vertex = args.vertex;
    }
  }
};
Pyd2botService_moveToVertex_args.prototype = {};
Pyd2botService_moveToVertex_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.vertex = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Pyd2botService_moveToVertex_args.prototype.write = function(output) {
  output.writeStructBegin('Pyd2botService_moveToVertex_args');
  if (this.vertex !== null && this.vertex !== undefined) {
    output.writeFieldBegin('vertex', Thrift.Type.STRING, 1);
    output.writeString(this.vertex);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Pyd2botService_moveToVertex_result = function(args) {
};
Pyd2botService_moveToVertex_result.prototype = {};
Pyd2botService_moveToVertex_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Pyd2botService_moveToVertex_result.prototype.write = function(output) {
  output.writeStructBegin('Pyd2botService_moveToVertex_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Pyd2botService_followTransition_args = function(args) {
  this.transition = null;
  if (args) {
    if (args.transition !== undefined && args.transition !== null) {
      this.transition = args.transition;
    }
  }
};
Pyd2botService_followTransition_args.prototype = {};
Pyd2botService_followTransition_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.transition = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Pyd2botService_followTransition_args.prototype.write = function(output) {
  output.writeStructBegin('Pyd2botService_followTransition_args');
  if (this.transition !== null && this.transition !== undefined) {
    output.writeFieldBegin('transition', Thrift.Type.STRING, 1);
    output.writeString(this.transition);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Pyd2botService_followTransition_result = function(args) {
};
Pyd2botService_followTransition_result.prototype = {};
Pyd2botService_followTransition_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Pyd2botService_followTransition_result.prototype.write = function(output) {
  output.writeStructBegin('Pyd2botService_followTransition_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Pyd2botService_getStatus_args = function(args) {
};
Pyd2botService_getStatus_args.prototype = {};
Pyd2botService_getStatus_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Pyd2botService_getStatus_args.prototype.write = function(output) {
  output.writeStructBegin('Pyd2botService_getStatus_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Pyd2botService_getStatus_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
Pyd2botService_getStatus_result.prototype = {};
Pyd2botService_getStatus_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Pyd2botService_getStatus_result.prototype.write = function(output) {
  output.writeStructBegin('Pyd2botService_getStatus_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Pyd2botService_comeToBankToCollectResources_args = function(args) {
  this.bankInfos = null;
  this.guestInfos = null;
  if (args) {
    if (args.bankInfos !== undefined && args.bankInfos !== null) {
      this.bankInfos = args.bankInfos;
    }
    if (args.guestInfos !== undefined && args.guestInfos !== null) {
      this.guestInfos = args.guestInfos;
    }
  }
};
Pyd2botService_comeToBankToCollectResources_args.prototype = {};
Pyd2botService_comeToBankToCollectResources_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.bankInfos = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.guestInfos = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Pyd2botService_comeToBankToCollectResources_args.prototype.write = function(output) {
  output.writeStructBegin('Pyd2botService_comeToBankToCollectResources_args');
  if (this.bankInfos !== null && this.bankInfos !== undefined) {
    output.writeFieldBegin('bankInfos', Thrift.Type.STRING, 1);
    output.writeString(this.bankInfos);
    output.writeFieldEnd();
  }
  if (this.guestInfos !== null && this.guestInfos !== undefined) {
    output.writeFieldBegin('guestInfos', Thrift.Type.STRING, 3);
    output.writeString(this.guestInfos);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Pyd2botService_comeToBankToCollectResources_result = function(args) {
};
Pyd2botService_comeToBankToCollectResources_result.prototype = {};
Pyd2botService_comeToBankToCollectResources_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Pyd2botService_comeToBankToCollectResources_result.prototype.write = function(output) {
  output.writeStructBegin('Pyd2botService_comeToBankToCollectResources_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Pyd2botService_getCurrentVertex_args = function(args) {
};
Pyd2botService_getCurrentVertex_args.prototype = {};
Pyd2botService_getCurrentVertex_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Pyd2botService_getCurrentVertex_args.prototype.write = function(output) {
  output.writeStructBegin('Pyd2botService_getCurrentVertex_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Pyd2botService_getCurrentVertex_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
Pyd2botService_getCurrentVertex_result.prototype = {};
Pyd2botService_getCurrentVertex_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Pyd2botService_getCurrentVertex_result.prototype.write = function(output) {
  output.writeStructBegin('Pyd2botService_getCurrentVertex_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Pyd2botServiceClient = exports.Client = function(output, pClass) {
  this.output = output;
  this.pClass = pClass;
  this._seqid = 0;
  this._reqs = {};
};
Pyd2botServiceClient.prototype = {};
Pyd2botServiceClient.prototype.seqid = function() { return this._seqid; };
Pyd2botServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };

Pyd2botServiceClient.prototype.getApiKey = function(login, password, certId, certHash, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getApiKey(login, password, certId, certHash);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getApiKey(login, password, certId, certHash);
  }
};

Pyd2botServiceClient.prototype.send_getApiKey = function(login, password, certId, certHash) {
  var output = new this.pClass(this.output);
  var params = {
    login: login,
    password: password,
    certId: certId,
    certHash: certHash
  };
  var args = new Pyd2botService_getApiKey_args(params);
  try {
    output.writeMessageBegin('getApiKey', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

Pyd2botServiceClient.prototype.recv_getApiKey = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Pyd2botService_getApiKey_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getApiKey failed: unknown result');
};

Pyd2botServiceClient.prototype.fetchAccountCharacters = function(login, password, certId, certHash, apiKey, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_fetchAccountCharacters(login, password, certId, certHash, apiKey);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_fetchAccountCharacters(login, password, certId, certHash, apiKey);
  }
};

Pyd2botServiceClient.prototype.send_fetchAccountCharacters = function(login, password, certId, certHash, apiKey) {
  var output = new this.pClass(this.output);
  var params = {
    login: login,
    password: password,
    certId: certId,
    certHash: certHash,
    apiKey: apiKey
  };
  var args = new Pyd2botService_fetchAccountCharacters_args(params);
  try {
    output.writeMessageBegin('fetchAccountCharacters', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

Pyd2botServiceClient.prototype.recv_fetchAccountCharacters = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Pyd2botService_fetchAccountCharacters_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('fetchAccountCharacters failed: unknown result');
};

Pyd2botServiceClient.prototype.runSession = function(login, password, certId, certHash, apiKey, sessionJson, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_runSession(login, password, certId, certHash, apiKey, sessionJson);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_runSession(login, password, certId, certHash, apiKey, sessionJson);
  }
};

Pyd2botServiceClient.prototype.send_runSession = function(login, password, certId, certHash, apiKey, sessionJson) {
  var output = new this.pClass(this.output);
  var params = {
    login: login,
    password: password,
    certId: certId,
    certHash: certHash,
    apiKey: apiKey,
    sessionJson: sessionJson
  };
  var args = new Pyd2botService_runSession_args(params);
  try {
    output.writeMessageBegin('runSession', Thrift.MessageType.ONEWAY, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    this.output.flush();
    var callback = this._reqs[this.seqid()] || function() {};
    delete this._reqs[this.seqid()];
    callback(null);
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

Pyd2botServiceClient.prototype.fetchBreedSpells = function(breedId, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_fetchBreedSpells(breedId);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_fetchBreedSpells(breedId);
  }
};

Pyd2botServiceClient.prototype.send_fetchBreedSpells = function(breedId) {
  var output = new this.pClass(this.output);
  var params = {
    breedId: breedId
  };
  var args = new Pyd2botService_fetchBreedSpells_args(params);
  try {
    output.writeMessageBegin('fetchBreedSpells', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

Pyd2botServiceClient.prototype.recv_fetchBreedSpells = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Pyd2botService_fetchBreedSpells_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('fetchBreedSpells failed: unknown result');
};

Pyd2botServiceClient.prototype.fetchJobsInfosJson = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_fetchJobsInfosJson();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_fetchJobsInfosJson();
  }
};

Pyd2botServiceClient.prototype.send_fetchJobsInfosJson = function() {
  var output = new this.pClass(this.output);
  var args = new Pyd2botService_fetchJobsInfosJson_args();
  try {
    output.writeMessageBegin('fetchJobsInfosJson', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

Pyd2botServiceClient.prototype.recv_fetchJobsInfosJson = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Pyd2botService_fetchJobsInfosJson_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('fetchJobsInfosJson failed: unknown result');
};

Pyd2botServiceClient.prototype.moveToVertex = function(vertex, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_moveToVertex(vertex);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_moveToVertex(vertex);
  }
};

Pyd2botServiceClient.prototype.send_moveToVertex = function(vertex) {
  var output = new this.pClass(this.output);
  var params = {
    vertex: vertex
  };
  var args = new Pyd2botService_moveToVertex_args(params);
  try {
    output.writeMessageBegin('moveToVertex', Thrift.MessageType.ONEWAY, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    this.output.flush();
    var callback = this._reqs[this.seqid()] || function() {};
    delete this._reqs[this.seqid()];
    callback(null);
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

Pyd2botServiceClient.prototype.followTransition = function(transition, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_followTransition(transition);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_followTransition(transition);
  }
};

Pyd2botServiceClient.prototype.send_followTransition = function(transition) {
  var output = new this.pClass(this.output);
  var params = {
    transition: transition
  };
  var args = new Pyd2botService_followTransition_args(params);
  try {
    output.writeMessageBegin('followTransition', Thrift.MessageType.ONEWAY, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    this.output.flush();
    var callback = this._reqs[this.seqid()] || function() {};
    delete this._reqs[this.seqid()];
    callback(null);
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

Pyd2botServiceClient.prototype.getStatus = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getStatus();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getStatus();
  }
};

Pyd2botServiceClient.prototype.send_getStatus = function() {
  var output = new this.pClass(this.output);
  var args = new Pyd2botService_getStatus_args();
  try {
    output.writeMessageBegin('getStatus', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

Pyd2botServiceClient.prototype.recv_getStatus = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Pyd2botService_getStatus_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getStatus failed: unknown result');
};

Pyd2botServiceClient.prototype.comeToBankToCollectResources = function(bankInfos, guestInfos, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_comeToBankToCollectResources(bankInfos, guestInfos);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_comeToBankToCollectResources(bankInfos, guestInfos);
  }
};

Pyd2botServiceClient.prototype.send_comeToBankToCollectResources = function(bankInfos, guestInfos) {
  var output = new this.pClass(this.output);
  var params = {
    bankInfos: bankInfos,
    guestInfos: guestInfos
  };
  var args = new Pyd2botService_comeToBankToCollectResources_args(params);
  try {
    output.writeMessageBegin('comeToBankToCollectResources', Thrift.MessageType.ONEWAY, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    this.output.flush();
    var callback = this._reqs[this.seqid()] || function() {};
    delete this._reqs[this.seqid()];
    callback(null);
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

Pyd2botServiceClient.prototype.getCurrentVertex = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getCurrentVertex();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getCurrentVertex();
  }
};

Pyd2botServiceClient.prototype.send_getCurrentVertex = function() {
  var output = new this.pClass(this.output);
  var args = new Pyd2botService_getCurrentVertex_args();
  try {
    output.writeMessageBegin('getCurrentVertex', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

Pyd2botServiceClient.prototype.recv_getCurrentVertex = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Pyd2botService_getCurrentVertex_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getCurrentVertex failed: unknown result');
};
var Pyd2botServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
};
Pyd2botServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
};
Pyd2botServiceProcessor.prototype.process_getApiKey = function(seqid, input, output) {
  var args = new Pyd2botService_getApiKey_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getApiKey.length === 4) {
    Q.fcall(this._handler.getApiKey.bind(this._handler),
      args.login,
      args.password,
      args.certId,
      args.certHash
    ).then(function(result) {
      var result_obj = new Pyd2botService_getApiKey_result({success: result});
      output.writeMessageBegin("getApiKey", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("getApiKey", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.getApiKey(args.login, args.password, args.certId, args.certHash, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new Pyd2botService_getApiKey_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("getApiKey", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getApiKey", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
Pyd2botServiceProcessor.prototype.process_fetchAccountCharacters = function(seqid, input, output) {
  var args = new Pyd2botService_fetchAccountCharacters_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.fetchAccountCharacters.length === 5) {
    Q.fcall(this._handler.fetchAccountCharacters.bind(this._handler),
      args.login,
      args.password,
      args.certId,
      args.certHash,
      args.apiKey
    ).then(function(result) {
      var result_obj = new Pyd2botService_fetchAccountCharacters_result({success: result});
      output.writeMessageBegin("fetchAccountCharacters", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("fetchAccountCharacters", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.fetchAccountCharacters(args.login, args.password, args.certId, args.certHash, args.apiKey, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new Pyd2botService_fetchAccountCharacters_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("fetchAccountCharacters", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("fetchAccountCharacters", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
Pyd2botServiceProcessor.prototype.process_runSession = function(seqid, input, output) {
  var args = new Pyd2botService_runSession_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.runSession(args.login, args.password, args.certId, args.certHash, args.apiKey, args.sessionJson);
};
Pyd2botServiceProcessor.prototype.process_fetchBreedSpells = function(seqid, input, output) {
  var args = new Pyd2botService_fetchBreedSpells_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.fetchBreedSpells.length === 1) {
    Q.fcall(this._handler.fetchBreedSpells.bind(this._handler),
      args.breedId
    ).then(function(result) {
      var result_obj = new Pyd2botService_fetchBreedSpells_result({success: result});
      output.writeMessageBegin("fetchBreedSpells", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("fetchBreedSpells", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.fetchBreedSpells(args.breedId, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new Pyd2botService_fetchBreedSpells_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("fetchBreedSpells", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("fetchBreedSpells", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
Pyd2botServiceProcessor.prototype.process_fetchJobsInfosJson = function(seqid, input, output) {
  var args = new Pyd2botService_fetchJobsInfosJson_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.fetchJobsInfosJson.length === 0) {
    Q.fcall(this._handler.fetchJobsInfosJson.bind(this._handler)
    ).then(function(result) {
      var result_obj = new Pyd2botService_fetchJobsInfosJson_result({success: result});
      output.writeMessageBegin("fetchJobsInfosJson", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("fetchJobsInfosJson", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.fetchJobsInfosJson(function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new Pyd2botService_fetchJobsInfosJson_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("fetchJobsInfosJson", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("fetchJobsInfosJson", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
Pyd2botServiceProcessor.prototype.process_moveToVertex = function(seqid, input, output) {
  var args = new Pyd2botService_moveToVertex_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.moveToVertex(args.vertex);
};
Pyd2botServiceProcessor.prototype.process_followTransition = function(seqid, input, output) {
  var args = new Pyd2botService_followTransition_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.followTransition(args.transition);
};
Pyd2botServiceProcessor.prototype.process_getStatus = function(seqid, input, output) {
  var args = new Pyd2botService_getStatus_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getStatus.length === 0) {
    Q.fcall(this._handler.getStatus.bind(this._handler)
    ).then(function(result) {
      var result_obj = new Pyd2botService_getStatus_result({success: result});
      output.writeMessageBegin("getStatus", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("getStatus", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.getStatus(function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new Pyd2botService_getStatus_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("getStatus", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getStatus", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
Pyd2botServiceProcessor.prototype.process_comeToBankToCollectResources = function(seqid, input, output) {
  var args = new Pyd2botService_comeToBankToCollectResources_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.comeToBankToCollectResources(args.bankInfos, args.guestInfos);
};
Pyd2botServiceProcessor.prototype.process_getCurrentVertex = function(seqid, input, output) {
  var args = new Pyd2botService_getCurrentVertex_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getCurrentVertex.length === 0) {
    Q.fcall(this._handler.getCurrentVertex.bind(this._handler)
    ).then(function(result) {
      var result_obj = new Pyd2botService_getCurrentVertex_result({success: result});
      output.writeMessageBegin("getCurrentVertex", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("getCurrentVertex", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.getCurrentVertex(function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new Pyd2botService_getCurrentVertex_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("getCurrentVertex", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getCurrentVertex", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
