
class LuaFormulasEnum:
    MONSTER_XP = 2
    JOBLEVELUP_PODSBONUS = 46
    BREACH_ROOM_DIFFICULTY = 56
    BREACH_EXP_MULTIPLIER = 69
    BREACH_MONSTER_HIDDEN_LEVEL = 70
    XP_TO_CHARACTER_LEVEL = 74
    CHARACTER_LEVEL_TO_XP = 77
    TEMPOKEN_TO_XP = 84
    MAX_GUILD_MEMBERS = 94