class StatesEnum:

    STATE_NORMAL: int = 0

    STATE_OVER: int = 1

    STATE_CLICKED: int = 2

    STATE_SELECTED: int = 3

    STATE_SELECTED_OVER: int = 4

    STATE_SELECTED_CLICKED: int = 5

    STATE_DISABLED: int = 6

    STATE_NORMAL_STRING: str = "NORMAL"

    STATE_OVER_STRING: str = "OVER"

    STATE_CLICKED_STRING: str = "PRESSED"

    STATE_DISABLED_STRING: str = "DISABLED"

    STATE_SELECTED_STRING: str = "SELECTED"

    STATE_SELECTED_OVER_STRING: str = "SELECTED_OVER"

    STATE_SELECTED_CLICKED_STRING: str = "SELECTED_PRESSED"
