class ZAAP_CONFIG:
    class USER_ACCOUNT_LOCKED:
        MAILNOVALID = 2
    ZAAP_GAME_ID = 102
        
class AUTH_STATES:
    UNAUTHETICATED = "UNAUTHENTICATED",
    USER_EMAIL_INVALID = "USER_EMAIL_INVALID",
    NOT_AUTHENTICATED = "NOT_AUTHENTICATED",
    AUTHENTICATED = "AUTHENTICATED",
    NEED_DOUBLE_AUTH= "NEED_DOUBLE_AUTH",
    CODE_SENT= "CODE_SENT",
    CODE_INCORRECT= "CODE_INCORRECT",
    CODE_EXPIRED= "CODE_EXPIRED",
    ERRORED= "ERRORED",
    NONEED_TOBE_SECURED= "NONEEDTOBESECURED",
    ALREADYSECURED= "ALREADYSECURED",